#!/usr/bin/env bash
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_a1 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.01 --kernel_r 0.0001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_a2 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.01 --kernel_r 0.001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_a3 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.01 --kernel_r 0.01 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_a4 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.01 --kernel_r 0.1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_a5 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.01 --kernel_r 1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_a6 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.01 --kernel_r 10 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_b1 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.1 --kernel_r 0.0001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_b2 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.1 --kernel_r 0.001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_b3 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.1 --kernel_r 0.01 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_b4 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.1 --kernel_r 0.1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_b5 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.1 --kernel_r 1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_b6 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 0.1 --kernel_r 10 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_c1 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 1 --kernel_r 0.0001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_c2 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 1 --kernel_r 0.001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_c3 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 1 --kernel_r 0.01 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_c4 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 1 --kernel_r 0.1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_c5 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 1 --kernel_r 1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_c6 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 1 --kernel_r 10 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_d1 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 10 --kernel_r 0.0001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_d2 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 10 --kernel_r 0.001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_d3 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 10 --kernel_r 0.01 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_d4 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 10 --kernel_r 0.1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_d5 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 10 --kernel_r 1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_d6 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 10 --kernel_r 10 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_e1 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 100 --kernel_r 0.0001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_e2 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 100 --kernel_r 0.001 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_e3 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 100 --kernel_r 0.01 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_e4 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 100 --kernel_r 0.1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_e5 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 100 --kernel_r 1 --num_return_sequences 1
python3 T5_SQuAD_QG_With_GPP.py --trim_train_pct 0.1 --flag grid_e6 --encoder_max_length 64 --epochs 5 --batch_size 32 --kernel_v 100 --kernel_r 10 --num_return_sequences 1
